experimental-features = nix-command flakes
extra-platforms = x86_64-darwin aarch64-darwin
substituters = https://cache.nixos.org https://helix.cachix.org
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= helix.cachix.org-1:ejp9KQpR1FBI2onstMQ34yogDm4OgU2ru6lIwPvuCVs=
