unbind C-b
set-option -g prefix C-Space

set -g base-index 1
set-option -g renumber-windows on


set -g mouse on
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",xterm-ghostty:RGB"
bind -T copy-mode M-Up send-keys -X page-up
bind -T copy-mode M-Down send-keys -X page-down
set-option -g focus-events on
set -sg escape-time 0

set -g status-position top
set -g status-justify absolute-centre
set -g status-style "bg=default"
set -g window-status-current-style "fg=black bg=white"
set -g status-interval 5
set -g status-left "#S"
set -g status-right ""
      
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

bind f display-popup -E "~/dotfiles/scripts/tmux-session.sh"
bind o display-popup -E "~/dotfiles/scripts/open-files.sh"
