[config]
layout = [
	"######     ######",
	"######     ######",
	"######     ######",
	"######## ########",
	"   ##### #####   ",
	"#####       #####",
]
layers = ["BASE", "NAV", "SYM"]


[format]
padding = 2

[config.features.chordal_hold]
enabled = true
mode = "none"
tapping_term = 200
retro_tapping = true    
