[config]
layout = [
	"######     ######",
	"######     ######",
	"######     ######",
	"######## ########",
	"   ##### #####   ",
	"#####       #####",
]
layers = ["BASE", "NAV", "SYM"]


[format]
padding = 2

