theme = "base"


[editor]
bufferline = "always"
true-color = true
color-modes = true
cursorline = true
line-number = "relative"
popup-border = "all"
completion-trigger-len = 1
continue-comments = false
idle-timeout = 250
completion-timeout = 5
scrolloff = 10

[editor.search]
smart-case = true

[editor.soft-wrap]
enable = true
max-wrap = 20
max-indent-retain = 0
wrap-indicator = ""

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["version-control","workspace-diagnostics" ]
right = ["diagnostics", "file-type","position-percentage", "total-line-numbers"]

[editor.indent-guides]
render = true
character = "┆"
skip-levels = 0

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.lsp]
display-messages = true
auto-signature-help = true
[editor.file-picker]
hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "underline"
select = "underline"

[keys.normal]
"+" = ":format"
"tab" = ":buffer-next"
"S-tab" = ":buffer-previous"
H = "goto_line_start"
L = "goto_line_end"
J = "page_cursor_half_down"
K = "page_cursor_half_up"

[keys.normal.space]
x = ":buffer-close"
X = ":buffer-close!"

[keys.normal.space.n]
n = "@:sh touch "
N = "@:sh touch <C-r>%<C-w>"
d = "@:sh mkdir -p "
D = "@:sh mkdir -p <C-r>%<C-w>"
r = "@:sh rm <C-r>%"
R = "@:sh rm <C-r>%<C-w>"
m = "@:sh mv <C-r>% "
M = "@:sh mv <C-r>% <C-r>%<C-w>"
p = "@:sh cp <C-r>% "

[keys.select]
H = "goto_line_start"
L = "goto_line_end"
J = "page_cursor_half_down"
K = "page_cursor_half_up"
