vim.o.winborder = 'none'
vim.o.tabstop = 4
vim.o.shiftwidth = 4
vim.o.showtabline = 0
vim.o.signcolumn = 'yes'
vim.o.cursorcolumn = false
vim.o.ignorecase = true
vim.o.wrap = false
vim.o.smartindent = true
vim.o.termguicolors = true
vim.o.undofile = true
vim.o.number = true
vim.o.relativenumber = true
vim.o.autoread = true
vim.o.swapfile = false
vim.g.mapleader = ' '
vim.cmd([[hi @lsp.type.number gui=bold]])
vim.cmd('autocmd BufEnter * set formatoptions-=cro')
vim.cmd('autocmd BufEnter * setlocal formatoptions-=cro')
